spring.application.name=todoapp

# Konsolda SQL sorgularini gormek icin
spring.jpa.show-sql=true

# PostgreSQL Veritabani Baglantisi
spring.datasource.url=jdbc:postgresql://localhost:5432/todo_db
spring.datasource.username=postgres
spring.datasource.password=akyurt510

# JPA / Hibernate Ayarlari
# update: Tablo yoksa olusturur, varsa sadece degisiklikleri (yeni sutun vb.) ekler.
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# Hibernate'in isimlendirme stratejisi (snake_case icin)
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

# JWT Secret Key (Base64 encoded)
jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970

# S3 Configuration for MinIO
spring.cloud.aws.s3.endpoint=http://localhost:9000
spring.cloud.aws.s3.path-style-access-enabled=true
spring.cloud.aws.region.static=us-east-1
spring.cloud.aws.credentials.access-key=minioadmin
spring.cloud.aws.credentials.secret-key=minioadmin
spring.cloud.aws.s3.bucket=todoapp
